# Generated by Django 4.2.1 on 2023-05-12 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0002_alter_infopersoane_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='infopersoane',
            options={'verbose_name_plural': 'InfoPersoane'},
        ),
    ]
