# Generated by Django 4.2.1 on 2023-05-13 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0003_alter_infopersoane_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('emails', models.EmailField(max_length=254, unique=True)),
                ('cards', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='InfoPersoane',
        ),
    ]
