# Generated by Django 4.2.1 on 2023-05-13 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0004_table_delete_infopersoane'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='emails',
            field=models.EmailField(max_length=254),
        ),
    ]
